// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBko3d4f8auz1BKqqjc40ZyYxam85qljBc',
    appId: '1:529825431904:web:5c7483cc5822b037109e05',
    messagingSenderId: '529825431904',
    projectId: 'dhaka-bus-tracker-327-454d1',
    authDomain: 'dhaka-bus-tracker-327-454d1.firebaseapp.com',
    storageBucket: 'dhaka-bus-tracker-327-454d1.firebasestorage.app',
    measurementId: 'G-E64R5688RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY0CT8THq9Vs0ublsEnFLYsT7u3EdCVc0',
    appId: '1:529825431904:android:8d9d451ae2ebf60e109e05',
    messagingSenderId: '529825431904',
    projectId: 'dhaka-bus-tracker-327-454d1',
    storageBucket: 'dhaka-bus-tracker-327-454d1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBko3d4f8auz1BKqqjc40ZyYxam85qljBc',
    appId: '1:529825431904:web:3535a0452dcf0b17109e05',
    messagingSenderId: '529825431904',
    projectId: 'dhaka-bus-tracker-327-454d1',
    authDomain: 'dhaka-bus-tracker-327-454d1.firebaseapp.com',
    storageBucket: 'dhaka-bus-tracker-327-454d1.firebasestorage.app',
    measurementId: 'G-5WJSPTWLK3',
  );
}
